services:
  # nosemgrep
  emba:
    image: embeddedanalyzer/emba:1.5.1b
    container_name: emba
    read_only: true
    # all pre-checker mount modules need privileged mode
    # nosemgrep
    privileged: true
    # /root/.config is needed for binwalk - further recovery for other tools needed
    # /root/.config is needed for cwe_checker
    # /root/.local is needed for cwe_checker
    tmpfs:
      # exec on /tmp is needed for capa -> Todo: find better solution
      - /tmp:exec
      - /root/.config/
      - /root/.local/share/composer/
      - /root/.local/share/cwe_checker/
        # - /root/.local/share
      - /root/.cache/
      - /root/.semgrep/
      - /root/.ghidra/
      - /root/.msf4
      - /root/.john
      - /root/.gnupg
      - /run/lock
      - /var/run
      - /var/tmp
      - /var/lock
    build: .
    # /dev is needed for the system emulator (L10)
    volumes:
        - ${FIRMWARE}/:/firmware:ro
        - ${LOG}/:/logs
        - ${EMBA}/:/emba:ro
        - ${EMBA}/external/linux_kernel_sources/:/external/linux_kernel_sources:ro
        - ${EMBA}/external/nvd-json-data-feeds/:/external/nvd-json-data-feeds:ro
        - /etc/localtime:/etc/localtime:ro
        - /dev:/dev
    environment:
        - USER
        - CONTAINER_NUMBER=1
        - STRICT_MODE
        - DEBUG_SCRIPT
        - UPDATE
        - ARCH_CHECK
        - RTOS
        - BINARY_EXTENDED
        - MAX_EXT_CHECK_BINS
        - CONTAINER_EXTRACT
        - DISABLE_DEE
        - DEEP_EXT_DEPT
        - FACT_EXTRACTOR
        - FORCE
        - FORMAT_LOG
        - HTML
        - KERNEL
        - KERNEL_CONFIG
        - FIRMWARE_PATH
        - FIRMWARE_PATH1
        - DIFF_MODE
        - FW_VENDOR
        - FW_VERSION
        - FW_DEVICE
        - FW_NOTES
        - ARCH
        - EFI_ARCH
        - EXLUDE
        - MAX_MODS
        - MAX_MOD_THREADS
        - FINAL_FW_RM
        - ONLY_DEP
        - PHP_CHECK
        - PRE_CHECK
        - SKIP_PRE_CHECKERS
        - PYTHON_CHECK
        - L10_DEBUG_MODE
        - FULL_EMULATION
        - QEMULATION
        - L10_KERNEL_V_LONG
        - L10_BB_VER
        - FULL_TEST
        - QRUNTIME
        - SHELLCHECK
        - SHORT_PATH
        - THREADED
        - YARA
        - OVERWRITE_LOG
        - MAX_EXT_SPACE
        - PID_LOGGING
        - PID_LOG_FILE
        - SILENT
        - DISABLE_STATUS_BAR
        - DISABLE_NOTIFICATIONS
        - NOTIFICATION_ID
        - UNBLOB
        - Q_MOD_PID
        - F20_DEEP
        - UEFI_VERIFIED
        - DISABLE_DOTS
        - CPE_VERSION
        - SBOM_MAX_FILE_LOG
        - SBOM_MINIMAL
        - SBOM_UNTRACKED_FILES
    # network_mode: host
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    ulimits:
      core:
        hard: 0
        soft: 0

  emba_quest:
    image: embeddedanalyzer/emba:1.5.1b
    container_name: emba_quest
    read_only: true
    tmpfs:
      - /tmp
      - /root
      - /run/lock
      - /var/run
      - /var/tmp
      - /var/lock
    volumes:
        - ${FIRMWARE}/:/firmware:ro
        - ${LOG}/:/logs
        - ${EMBA}/:/emba:ro
        - ${EMBA}/external/linux_kernel_sources/:/external/linux_kernel_sources
        - ${EMBA}/external/nvd-json-data-feeds/:/external/nvd-json-data-feeds:ro
        - /etc/localtime:/etc/localtime:ro
    environment:
        - USER
        - CONTAINER_NUMBER=2
        - STRICT_MODE
        - DEBUG_SCRIPT
        - UPDATE
        - FORCE
        - FORMAT_LOG
        - HTML
        - EXLUDE
        - MAX_MODS
        - MAX_MOD_THREADS
        - FINAL_FW_RM
        - GPT_OPTION
        - GPT_QUESTION
        - MINIMUM_GPT_PRIO
        - SHORT_PATH
        - THREADED
        - OVERWRITE_LOG
        - MAX_EXT_SPACE
        - PID_LOGGING
        - PID_LOG_FILE
        - SILENT
        - DISABLE_STATUS_BAR
        - DISABLE_NOTIFICATIONS
        - Q_MOD_PID
        - DISABLE_DOTS
    network_mode: host
    ulimits:
      core:
        hard: 0
        soft: 0
    security_opt:
      - no-new-privileges:true

